# Étape de build
FROM node:18-alpine AS build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

# Étape de production serve
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
# Configuration nginx optionnelle
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
